"""empty message

Revision ID: 0f7174307237
Revises: 6005a26c6a5a
Create Date: 2023-01-27 18:15:00.307987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f7174307237'
down_revision = '6005a26c6a5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_id', sa.String(length=30), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.drop_column('stripe_id')

    # ### end Alembic commands ###
