"""empty message

Revision ID: 609d960013e4
Revises: e98089b2ea6a
Create Date: 2022-12-21 11:27:10.347668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '609d960013e4'
down_revision = 'e98089b2ea6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site', sa.String(length=4), nullable=True),
    sa.Column('car_plate', sa.String(length=30), nullable=True),
    sa.Column('user_id', sa.String(length=30), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('car_plate'),
    sa.UniqueConstraint('site'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('car',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plate', sa.String(length=9), nullable=True),
    sa.Column('brand', sa.String(length=30), nullable=True),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plate')
    )
    op.create_table('my_cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['car.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('car_id'),
    sa.UniqueConstraint('user_id')
    )
    op.add_column('user', sa.Column('name', sa.String(length=20), nullable=False))
    op.add_column('user', sa.Column('surname', sa.String(length=20), nullable=False))
    op.add_column('user', sa.Column('telephone', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('car_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'user', ['car_id'])
    op.create_unique_constraint(None, 'user', ['telephone'])
    op.create_foreign_key(None, 'user', 'car', ['car_id'], ['id'])
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'car_id')
    op.drop_column('user', 'telephone')
    op.drop_column('user', 'surname')
    op.drop_column('user', 'name')
    op.drop_table('my_cars')
    op.drop_table('car')
    op.drop_table('parking')
    op.drop_table('category')
    # ### end Alembic commands ###
