"""empty message

Revision ID: 65d0049f2417
Revises: 609d960013e4
Create Date: 2022-12-21 11:30:49.939976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65d0049f2417'
down_revision = '609d960013e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_car_id_key', 'user', type_='unique')
    op.drop_constraint('user_car_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'car_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('car_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_car_id_fkey', 'user', 'car', ['car_id'], ['id'])
    op.create_unique_constraint('user_car_id_key', 'user', ['car_id'])
    # ### end Alembic commands ###
