"""empty message

Revision ID: 7d861c38d62f
Revises: 6991c93703fc
Create Date: 2023-03-13 08:20:29.866958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d861c38d62f'
down_revision = '6991c93703fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.drop_constraint('contact_email_key', type_='unique')
        batch_op.drop_constraint('contact_telephone_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.create_unique_constraint('contact_telephone_key', ['telephone'])
        batch_op.create_unique_constraint('contact_email_key', ['email'])

    # ### end Alembic commands ###
