"""empty message

Revision ID: c40596467f32
Revises: 65d0049f2417
Create Date: 2022-12-21 16:51:01.816798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c40596467f32'
down_revision = '65d0049f2417'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('my_cars_car_id_key', 'my_cars', type_='unique')
    op.drop_constraint('my_cars_user_id_key', 'my_cars', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('my_cars_user_id_key', 'my_cars', ['user_id'])
    op.create_unique_constraint('my_cars_car_id_key', 'my_cars', ['car_id'])
    # ### end Alembic commands ###
