"""empty message

Revision ID: fdcebabc0e1e
Revises: 9af5395d25e3
Create Date: 2023-01-25 19:42:44.970927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdcebabc0e1e'
down_revision = '9af5395d25e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parking_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'parking', ['parking_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('parking_id')

    # ### end Alembic commands ###
